version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - "8001:8001"
    restart: always

  client:
    build:
      context: ./client
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - server
networks:
  default:
    driver: bridge